### ISSUE TITLE
question about creating my own dataset

### ISSUE THREAD

**Issue by Miranda0920** [OpenDriveLab/OpenLane-V2#100]
Hello, thanks for your great work!
I wanna create my own dataset following openlanev2 format. I use "draw_annotation_pv()" function and  "draw_annotation_bev()" function to visualize my data, the pv picture seems normal, but bev picture has nothing to show.
![企业微信截图_17083299353685](https://github.com/OpenDriveLab/OpenLane-V2/assets/19873896/12551043-c12c-4457-aae7-241a4c86cc80)
![企业微信截图_17083299488601](https://github.com/OpenDriveLab/OpenLane-V2/assets/19873896/ad5afb86-f58d-4e88-a7ae-ee0285199c62)

 When I looked into the function, I found the parameter "BEV_SCALE" and "BEV_RANGE" may affect my result.
So, my questions are:
1. Can I use draw_annotation_bev() function to draw my data?
2. What coordinate are these lane_centerline['points'] located in?
3. Do the parameters "BEV_SCALE" and "BEV_RANGE"  matter? And how to set them?

**Comment by sephyli** [comment]
Hi @Miranda0920. Sorry for the late reply!

1. Certainly, you can proceed after aligning the data format and the BEV coordinates.
2. The data are in the ego coordinate system, where the ego is at (0, 0), with x-forward and y-left.
3. The `BEV_RANGE` defaults to ±50m in the x-direction and ±25m in the y-direction relative to the ego vehicle. The `BEV_SCALE` determines the resolution of your BEV image, measured in pixels per meter.

Please feel free to reach out!

**Comment by scuizhibin** [comment]
> Hello, thanks for your great work! I wanna create my own dataset following openlanev2 format. I use "draw_annotation_pv()" function and "draw_annotation_bev()" function to visualize my data, the pv picture seems normal, but bev picture has nothing to show. ![企业微信截图_17083299353685](https://private-user-images.githubusercontent.com/19873896/305872450-12551043-c12c-4457-aae7-241a4c86cc80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTM3NTAsIm5iZiI6MTczMTg5MzQ1MCwicGF0aCI6Ii8xOTg3Mzg5Ni8zMDU4NzI0NTAtMTI1NTEwNDMtYzEyYy00NDU3LWFhZTctMjQxYTRjODZjYzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAxMzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNWUzZTQ0YWNlM2FlNGNhOGVjODkxYTdjOWMzOTUwYzUxZWViYmZlZmFjNGViYTMwZTdiZTQwZDczMzY1ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IEFtBQ00JP1CW5OqW4VEbHku6nm6kjPt1Bfbu8immaA) ![企业微信截图_17083299488601](https://private-user-images.githubusercontent.com/19873896/305872504-ad5afb86-f58d-4e88-a7ae-ee0285199c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTM3NTAsIm5iZiI6MTczMTg5MzQ1MCwicGF0aCI6Ii8xOTg3Mzg5Ni8zMDU4NzI1MDQtYWQ1YWZiODYtZjU4ZC00ZTg4LWE3YWUtZWUwMjg1MTk5YzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAxMzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YTQzMTMwOTI1Y2EyOWU2NzQxNjE1Y2I5MzE4YzQwNTM5YjEwYTkxODg1OWQ0YTYxYmQ5MDJjMWYwMmQxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zV7ZyhRzsOv9V6bYUKExjxew57lqw6es5yjYNeVxOfI)
> 
> When I looked into the function, I found the parameter "BEV_SCALE" and "BEV_RANGE" may affect my result. So, my questions are:
> 
> 1. Can I use draw_annotation_bev() function to draw my data?
> 2. What coordinate are these lane_centerline['points'] located in?
> 3. Do the parameters "BEV_SCALE" and "BEV_RANGE"  matter? And how to set them?

How can I create my own data? Do I need to mark the lane markings myself?
