### ISSUE TITLE
Data correspondence between subset_A & Argoverse2

### ISSUE THREAD

**Issue by Wolfybox** [OpenDriveLab/OpenLane-V2#101]
similar question to https://github.com/OpenDriveLab/OpenLane-V2/issues/78, but for subset_A & Argoverse2

is it possible to also associate each frame in subset_A with that in Argoverse2 ?

**Comment by Wolfybox** [comment]
> Sure, you can use the `source_id` to track back to the Argoverse 2 scene, and then use timestamps to find the relative frame.

nice, thanks a lot.

**Comment by elkolbo** [comment]
Hello can you please specify more closely how this relation works? Or can you guide me to a resource showing the overall structure of the 2 datasets. 
In argoverse there are much more camera samples in a folder for a specifc scene that can be found with the source_id token. How are the camera samples chosen that are passed on to openlanev2 dataset?
My goal is to add the lidar data to the openlanev2 subset a.
Another question: Why are there way more image files in argoverse compared to openlanev2?

**Comment by sephyli** [comment]
@elkolbo The frames from argoverse2 and OpenLane-V2 are 1-to-1 mapped. You can use the `source_id` [here](https://github.com/OpenDriveLab/OpenLane-V2/tree/master/data#meta-data) to track back to the Argoverse 2 scene.

**Comment by sephyli** [comment]
We downsampled the 10Hz camera samples to 2Hz, and then find the time-nearest images for each frame. You may need to use the timestamp to find the nearest LiDAR too.
