### ISSUE TITLE
question about the assignment in Top_lcte

### ISSUE THREAD

**Issue by ShangGL123** [OpenDriveLab/OpenLane-V2#104]
Hello, thank you for your work! I have a question when calculating Top-lcte. As shown in the figure below, why doesn't it consider [attribute] when calculating the matching result between te and GT in  Top-lcte as when calculating the mAP?  Will [Filter:lambda _:True] lead to category matching errors when using only boxes for matching? Thank you for correcting my confusion.
![image](https://github.com/OpenDriveLab/OpenLane-V2/assets/50814697/50e15b14-206c-4b54-8d04-39c8fd8697a7)

**Comment by ShangGL123** [comment]
Thank you for your reply! I noticed what you said, but I am curious whether it is reasonable to calculating the matching result based solely on coordinates? Or what are the advantages of this strategy? Thank you for correcting my fusion.

**Comment by faikit** [comment]
What do you mean by e to calculating the matching result based solely on coordinates?

In the code above, the metric scores are calculated. But the matching result should be the outputs of the model.
