### ISSUE TITLE
filter train set gt labels

### ISSUE THREAD

**Issue by kaiyi98** [OpenDriveLab/OpenLane-V2#106]
hello，
I want to remove the extension lines in intersection that are not in the current direction in the -ls.json file. How should the logic of judgment be?

Thanks.

**Comment by faikit** [comment]
Hi, maybe you can utilize the direction and topology of the centerlines? The order of points represents the direction of centerlines.

**Comment by sephyli** [comment]
You can also use the key `is_intersection_or_connector` to filter the lane segments within the intersection.

**Comment by kaiyi98** [comment]
> You can also use the key `is_intersection_or_connector` to filter the lane segments within the intersection.

but I need to keep the centerlines that the current car might travel on.

**Comment by kaiyi98** [comment]
> Hi, maybe you can utilize the direction and topology of the centerlines? The order of points represents the direction of centerlines.

just  the vector from startpoint to endpoint？But when the car rotates, the angle between the vector and the car coordinate system changes.

**Comment by faikit** [comment]
> > You can also use the key `is_intersection_or_connector` to filter the lane segments within the intersection.
> 
> but I need to keep the centerlines that the current car might travel on.

The coordinate of the ego car is (0, 0) on the ground plane. This property may be used to filter the lane on which the ego car is driving. Then, the topology relationship on lane can be used to calculate lanes on which ego car might travel.
