### ISSUE TITLE
About traffic element detection wrong annotations

### ISSUE THREAD

**Issue by treasureqqm** [OpenDriveLab/OpenLane-V2#108]
Hi, authors, I’m interested in CVPR2024 AGC mapless driving challenge, and as for the traffic element detection task, I find some obvious wrong annotations, here is my question: Is it allowed to manually modify these labels when I am training the model? @sephyli

**Comment by sephyli** [comment]
Sorry for the inconvenience caused. 
You can modify the labels during the training phase manually. You could also share those labels to us to improve the dataset's quality.

**Comment by treasureqqm** [comment]
> Sorry for the inconvenience caused. You can modify the labels during the training phase manually. You could also share those labels to us to improve the dataset's quality.

@sephyli 我还是先优化模型，后面的精力再来处理数据。不过官方方便提供更准确（主要是指类别是准确性）的标注吗？然后通知所有的参赛者。

**Comment by sephyli** [comment]
我们暂时没有更新label的计划。如果您遇到共性的标注错误问题，我们可以在赛事结束后整体进行修正。
