### ISSUE TITLE
Not able to download dataset from Google Drive with wget command

### ISSUE THREAD

**Issue by meetb007** [OpenDriveLab/OpenLane-V2#109]
I'm not able to download the data set by wget command give in the md file:

`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Ni-L6u1MGKJRAfUXm39PdBIxdk_ntdc6' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Ni-L6u1MGKJRAfUXm39PdBIxdk_ntdc6" -O OpenLane-V2_sample.tar`

In the OpenLane-V2_sample.tar file, I'm getting html data of google page saying **Google Drive can't scan this file for viruses.** and Download anyway button.

**Comment by faikit** [comment]
Hi, please use the download anyway button.

**Comment by meetb007** [comment]
I want to use wget command. I'm using this data on server so, I won't be able to download it through GUI.
Please suggest some way to download the data through command line.
