### ISSUE TITLE
How to reproduce the results of the baseline method.

### ISSUE THREAD

**Issue by ProbeTS** [OpenDriveLab/OpenLane-V2#11]
Thanks for your dataset and baseline code!

Could you share the number and the type of GPUs that you use to reproduce the results?

Thanks for your attention!

**Comment by faikit** [comment]
Hi, here are some [info](https://github.com/OpenDriveLab/OpenLane-V2/issues/10#issuecomment-1469855642), also you can check out #3 and #10.

**Comment by ProbeTS** [comment]
Thanks for your detailed help which solves my problem.
