### ISSUE TITLE
Logic of Topology Annotation

### ISSUE THREAD

**Issue by sugar-fly** [OpenDriveLab/OpenLane-V2#111]
As shown in the following Figure, do you think this topology annotation is wrong? 
My understanding is that in this case, the right lane should look at the right traffic light, and the left lane should look at the left traffic light. The annotation here is that both the right and left lanes look at these two traffic lights. 
There are a lot of such cases in the testing set. Can you explain the logic behind this annotation? Thank you very much! 
![20240606-104449](https://github.com/OpenDriveLab/OpenLane-V2/assets/78684864/30a3d53a-203d-441d-8da9-1710b26493b4)

**Comment by sugar-fly** [comment]
The annotation logic is inconsistent with the paper description (see the following figure). Can the author help to answer it?

![image](https://github.com/OpenDriveLab/OpenLane-V2/assets/78684864/44a23548-3bc3-4c2f-b3d7-fd0debe8bfc2)

**Comment by sephyli** [comment]
Thanks for your question. We only consider the relationship with the left/right lane seperately when the traffic light has an explicit left turn or right turn shape.
