### ISSUE TITLE
lane_segment about data_dict_subset_A_train_lanesegnet.pkl

### ISSUE THREAD

**Issue by LePetitSirius** [OpenDriveLab/OpenLane-V2#112]
After parsing the file data_dict_subset_A_train_lanesegnet.pkl, We get dict_keys(['version','segment_id','meta_data','timestamp',sensor','annotatoin','pose'])
 I have two questions: 
1. Each lane_segment in the annotation has left_laneline_type and right_laneline_type.There are several types of this category and what does it mean? 
2. Is the lane segment under annotation under all views?How to distinguish the lane line in the front view?
Looking forward to your reply. Thank you

**Comment by sephyli** [comment]
1. The definition of laneline types is at [here](https://github.com/OpenDriveLab/OpenLane-V2/tree/master/data#map-element-bucket). 0 is none(virtual lane without visible marks), 1 is solid and 2 is dash.
2. Yes, the annotation are under BEV views. If yout want to filter out the front-view lanes, you can project the lanes to 2D space and check if they are in the camera space. Or you can just check if they are in the 3D areas of the front-view FOV.
