### ISSUE TITLE
How to obtain Map Origin, Latitude/Longitude Coordinates, and Direction?

### ISSUE THREAD

**Issue by rilab314** [OpenDriveLab/OpenLane-V2#113]
Hello, I am currently using OpenLane-V2 and have a question regarding the dataset. 
Do you have data related to the map origin, latitude/longitude coordinates, and direction?
Any guidance or pointers towards relevant documentation would be greatly appreciated. 
Thank you for your assistance!

**Comment by sephyli** [comment]
We don't have a detail documentation about this. This dataset is built on the Argoverse 2 and nuScenes datasets. The localization information reletive to the global(city) coordinate can be found in ego pose.
The coordinate between city coordinate and GPS coordinate like WGS84 can be easily transformed. You can find something at #52.
