### ISSUE TITLE
How to obtain more specific laneline category?

### ISSUE THREAD

**Issue by HatakeKiki** [OpenDriveLab/OpenLane-V2#114]
Thanks for your inspiring work in lane-level dataset!
I found the categories of laneline are simplied from 22 (as mentioned in V1 annotations) to only three (virtual, dashed, solid). I prefer the more specific laneline categories and is there a way to retrive them?

**Comment by sephyli** [comment]
Hi, @HatakeKiki. 
Here, we refer to "lane line" as the visible lane marking, which can be summarized as (virtual, dashed, solid). The line with multiple categories may refer to the "centerline," the category of which can be obtained from the traffic element-lane topology.
