### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by lebron-2016** [OpenDriveLab/OpenLane-V2#116]
您好，

请问如何解决这一问题
![image](https://github.com/user-attachments/assets/9d54f8be-df93-494c-8fdc-9655db3687f5)

**Comment by faikit** [comment]
Hi, please provide the name and link of file which you are downloading.

**Comment by lebron-2016** [comment]
> Hi, please provide the name and link of file which you are downloading.

您好，我通过google drive链接下载时都遇到了这一问题，例如：https://drive.usercontent.google.com/download?id=1Or-Nmsq4SU24KNe-cn9twVYVprYPUd_y&export=download&authuser=0

**Comment by faikit** [comment]
Hi, maybe you can try the Baidu Yun, the files are identical.
