### ISSUE TITLE
Traffic Element Recognition

### ISSUE THREAD

**Issue by SaraMo14** [OpenDriveLab/OpenLane-V2#117]
How to do Traffic Element Recognition with your repo on nuScenes frames?

**Comment by faikit** [comment]
Hi, this repo is for the OpenLane-V2 dataset and provide devkit to use the dataset. If you mean the deep learning task of traffic element recognition, please see related repos, including [TopoNet](https://github.com/OpenDriveLab/TopoNet) and [LaneSegNet](https://github.com/OpenDriveLab/LaneSegNet).
