### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by PeggyPeppa** [OpenDriveLab/OpenLane-V2#12]
Hi, can you explain the definition of topology evaluation in this task to help us have a better understanding?

**Comment by faikit** [comment]
Hi, here are some [details](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/docs/metrics.md#topology). We first build up a matching between gt and predicted instances that the number of nodes (centerlines or traffic elements) are equal in these two graphs, then we evaluate the AP on its predicted neighbors of each node and average over all nodes.

**Comment by PeggyPeppa** [comment]
Thanks, got it! Besides I want to know did the gt topology-lclc consider the incoming and outgoing relationship?

**Comment by faikit** [comment]
Yes it does, the adjacency matrices are asymmetric.

**Comment by PeggyPeppa** [comment]
So what is the true meaning of "1" in the matrices？ For example, analyze from the ith row, 1 in the jth meanings the outging line of it?

**Comment by faikit** [comment]
Each centerline has a direction for driving, from the starting point to the ending point.
Then in a lclc matrix, for a pair of instances i and j, [i, j] == 1 means that the ending point of i is connected to the starting point of j, and vice versa.

**Comment by PeggyPeppa** [comment]
Thanks a lot!
