### ISSUE TITLE
How to get Depth info from the datataset

### ISSUE THREAD

**Issue by BaophanN** [OpenDriveLab/OpenLane-V2#122]
Dear author, I am interested in using LSS (Lift-splat-shoot) to train my models on OpenLaneV2 dataset, however, this dataset requires Depth information. As far as I know, OpenLane v2 is built upon AgoverseV2 and Nuscenes which contains lidar depth. Is there anyway I can get this information? Thank you

**Comment by faikit** [comment]
Hi, you can acquire sparse depth information by projecting LiADR point clouds onto images. The datasets of nuScenes and AV2 contain LiDAR point clouds.

**Comment by BaophanN** [comment]
Thanks for your response. So does that means the lidar point cloud is not put into OpenLane-v2, Isn't it?

**Comment by faikit** [comment]
Yes, but there is a 1-1 mapping back to the nuScenes and AV2 dataset for each frame.
