### ISSUE TITLE
NuScenes Traffic Light Color

### ISSUE THREAD

**Issue by SaraMo14** [OpenDriveLab/OpenLane-V2#125]
Hi,
I am working on nuScenes and I need traffic light color information. How can I associate traffic light elements in nuScenes with traffic light status information from OpenLane-V2?

Thank you!

**Comment by faikit** [comment]
Hi, there is mapping information to the origin frame in nuScenesm and you can find it in the metadata of each frame.

**Comment by SaraMo14** [comment]
Thank you! And how do you relate the annotations of traffic elements and lane centerlines to the ego vehicle position at a given timestamp?

**Comment by sephyli** [comment]
For the annotation process, we transform all the map information to the ego coordinate and annotate the traffic elements and the relationship on the current ego frame. We use the localization results provided by the nuScenes and Argoverse 2 dataset to obtain the local map.

**Comment by SaraMo14** [comment]
Could you please link the code to transform the map information to the ego coordinate? 
What I am trying to do is integrating ego information from nuscenes at a given timestamp with relevant traffic light status from your work.

**Comment by sephyli** [comment]
If you are using OpenLane-V2 dataset subset B, all the annotations are already given under ego coordinate.

**Comment by SaraMo14** [comment]
Thank you!!
