### ISSUE TITLE
Problem for Eval

### ISSUE THREAD

**Issue by YilinGao-SHU** [OpenDriveLab/OpenLane-V2#16]
Greetings, we have the following problem during testing, is this a problem caused by the parameters?
TypeError: format results() got an unexpected keyword argument 'dump‘
The test command is: /nvme0n1/OpenLane_v2/mmdetection3d/tools/dist_test.sh /nvme0n1/OpenLane_v2/mmdetection3d/projects/openlanev2/OpenLane-V2/plugin/mmdet3d/configs/baseline.py /nvme0n1/OpenLane_v2/work_dirs/baseline/epoch_2.pth 8 --out=/nvme0n1/OpenLane_v2/work_dirs/out/out.pkl --format-only --eval-options dump=True dump_dir=/nvme0n1/OpenLane_v2/work_dirs visualization=True visualization_dir=/nvme0n1/OpenLane_v2/work_dirs/vis

**Comment by faikit** [comment]
Hi, I think using `--eval *` instead of `--format-only` would be okay.

**Comment by YilinGao-SHU** [comment]
Thanks so much, does it means we have to change --format-only --eval-options dump=True dump_dir=/nvme0n1/OpenLane_v2/work_dirs visualization=True visualization_dir=/nvme0n1/OpenLane_v2/work_dirs/vis to --eval --eval-options dump=True dump_dir=/nvme0n1/OpenLane_v2/work_dirs visualization=True visualization_dir=/nvme0n1/OpenLane_v2/work_dirs/vis

**Comment by YilinGao-SHU** [comment]
> Hi, I think using `--eval *` instead of `--format-only` would be okay.

Thanks, I will close this issue~
