### ISSUE TITLE
The rules about temporal information 

### ISSUE THREAD

**Issue by Lizhuoling** [OpenDriveLab/OpenLane-V2#19]
I am curious about whether there are some rules about the usage of temporal information (information from other timestamps except the current timestamp) in this competition. Can you ban the use of future frames officially?

**Comment by Lizhuoling** [comment]
Or can you directly ban the use of temporal information (data of other timestamps officially)?

**Comment by faikit** [comment]
Hi, no future frame is allowed during inference.
