### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by linxcan** [OpenDriveLab/OpenLane-V2#21]
Hello! Is the input of the evaluation function the control point of the Bezier curve or the 3D line? If the output of the model is the control point of the Bezier curve, do I need to convert the result into a 3D line for evaluation?

**Comment by faikit** [comment]
Hi, we are not using control points. To represent a centerline, we use a sequence of points located on the centerline. In the gts, 201 points represent a centerline. But for evaluation, we downsample to 11 points for efficiency concerns (https://github.com/OpenDriveLab/OpenLane-V2/blob/master/data/OpenLane-V2/preprocess.py#L31).

**Comment by linxcan** [comment]
Is each line of gt represented by 201 points, is it too much?

**Comment by faikit** [comment]
The range covered in a single frame is 100m x 50m in the BEV, we provide these in order to describe lanes in detail. Please feel free to choose arbitrary number of points to use in your case.

**Comment by linxcan** [comment]
OK.Thanks!
