### ISSUE TITLE
baseline_large performance

### ISSUE THREAD

**Issue by qwertyczx** [OpenDriveLab/OpenLane-V2#22]
Hello, is there some information about the result of baseline_large in evaluation?

**Comment by faikit** [comment]
Hi, we have some modifications on augmentation etc., but the following results on the val split can be used for reference:
```
OpenLane-V2 Score - 0.292732
    DET_l - 0.183719
    DET_l_chamfer - 0.168729
    DET_t - 0.457165
    TOP_ll - 0.022970
    TOP_lt - 0.143250
F-Score - 0.215878
```

**Comment by qwertyczx** [comment]
OK. Thanks!

**Comment by wudongming97** [comment]
> Hi, we have some modifications on augmentation etc., but the following results on the val split can be used for reference:
> 
> ```
> OpenLane-V2 Score - 0.292732
>     DET_l - 0.183719
>     DET_l_chamfer - 0.168729
>     DET_t - 0.457165
>     TOP_ll - 0.022970
>     TOP_lt - 0.143250
> F-Score - 0.215878
> ```

What is the relationship between the baseline_large and TopoNet https://github.com/OpenDriveLab/TopoNet ? I can see they sometimes share same hyper-parameters.

**Comment by faikit** [comment]
Hi, they are unrelative.

**Comment by YuanxianH** [comment]
> Hi, we have some modifications on augmentation etc., but the following results on the val split can be used for reference:
> 
> ```
> OpenLane-V2 Score - 0.292732
>     DET_l - 0.183719
>     DET_l_chamfer - 0.168729
>     DET_t - 0.457165
>     TOP_ll - 0.022970
>     TOP_lt - 0.143250
> F-Score - 0.215878
> ```

Will this version of the baseline be open-sourced in the future? If so, when? Thanks a lot.

**Comment by faikit** [comment]
Hi, this version is the [baseline_large](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/configs/baseline_large.py), the modification should not be huge. The reported scores might differ a bit since the change of code, data version, etc.

**Comment by YuanxianH** [comment]
Thank you for your reply. Would you mind sharing any additional data augmentation methods you have used compared to `baseline_large`? Something like random rotation or translation in BEV? 🤔 
Besides, is there any reference paper or code that can be referenced?  😄

**Comment by faikit** [comment]
The addtional augmentations is not new, you can find them in like camera-based 3d detection models or something similar.
