### ISSUE TITLE
Test Time

### ISSUE THREAD

**Issue by yuanpengtu** [OpenDriveLab/OpenLane-V2#27]
After submitting the test file to the website, there is no test result after more than an hour. The status keeps 'running', what is the reason for this?

**Comment by faikit** [comment]
Hi, the evaluation process is still running. We have limited resources on the EvalAI platform so this process might take time. Also, for efficiency concerns, we recommend using a small number of points (e.g., 10) to represent a centerline and limiting the number of predicted centerlines and traffic elements (e.g., 50).

**Comment by yuanpengtu** [comment]
Okay, got it.
