### ISSUE TITLE
Complete Leaderboard

### ISSUE THREAD

**Issue by yuanpengtu** [OpenDriveLab/OpenLane-V2#32]
Hi, since the submitted result can be made private, so when will the complete leaderboard results be available?

**Comment by faikit** [comment]
Hi, only public results will count.

**Comment by yuanpengtu** [comment]
Could you share the best result for all the submission? Now there are too few public submissions in the leaderboard, which have little reference value.

**Comment by faikit** [comment]
Hi, of course I am not allowed to do so.

**Comment by yuanpengtu** [comment]
Okay,
