### ISSUE TITLE
Chamfer Distance

### ISSUE THREAD

**Issue by artest08** [OpenDriveLab/OpenLane-V2#35]
Hello, 

In the issues, there is an indicated strong baseline. In that, chamfer distance is indicated as DET_l_chamfer. How is it calculated? Are thresholds again the same with Frechet Thresholds? Can we directly calculate it as below? 

    metrics['OpenLane-V2 Score']['DET_l_chamfer'] = _mAP_over_threshold(
        gts=gts, 
        preds=preds, 
        distance_matrixs=distance_matrixs['chamfer'], 
        distance_thresholds=THRESHOLDS_FRECHET,
        object_type='lane_centerline',
        filter=lambda _: True,
        inject=True, # save tp for eval on graph
    ).mean()

Thanks in advance

**Comment by faikit** [comment]
Hi, that is some obsolete code. For evaluation, please refer to the official [evaluation kit](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/openlanev2/evaluation/evaluate.py).
