### ISSUE TITLE
Error when trying to download data

### ISSUE THREAD

**Issue by akshaygopalkr** [OpenDriveLab/OpenLane-V2#37]
I see this error on Google Drive when trying to download the data:

"Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator."

Likewise, I am unable to download the data from the Baidu link.
Does anyone else see this error?

**Comment by hli2020** [comment]
Me too. cant download it from the Google link.

**Comment by faikit** [comment]
Hi, the links for me seems normal at this time. Maybe you can specify the file(s) which have an error. Also, we recommend using the links from OpenDataLab for downloading.
