### ISSUE TITLE
Questions About Matching Code

### ISSUE THREAD

**Issue by sumenpuyuan** [OpenDriveLab/OpenLane-V2#40]
https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/baseline/models/heads/custom_detr_head.py#L305
![image](https://user-images.githubusercontent.com/14249563/236817180-32d875d9-af83-4c10-b77f-58ef85aa8ab5.png)
According to the logic in the following lines, it can be inferred that the variable 'bbox_pred' is a normalized value with respect to the BEV boundary, while 'gt_bboxes' is the original 3D coordinate value. Are these two values unified in the matching function, or is there an issue with my code understanding?

**Comment by faikit** [comment]
Hi, I think you can try printing their values out.

**Comment by sumenpuyuan** [comment]
Actually, I have already printed these two variables and they seem to be the same as what I speculated. "pred" is the encoded version, while "gt" is the original content. However, when I passed these two variables into the matching function, I did not find any code that unifies them into the same dimension. This is exactly why I am confused. This is my first time dealing with set prediction algorithms, and I hope that someone experienced can help me out with this.

![image](https://user-images.githubusercontent.com/14249563/236977440-67a3ac60-24df-46dc-9710-351a00f81aff.png)

**Comment by faikit** [comment]
Hi, that might be a bug here, maybe you can have a look on [another model](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/configs/baseline_large.py).

**Comment by faikit** [comment]
Maybe applying the normalization in this [line](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/baseline/models/heads/custom_detr_head.py#L326) to [here](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/baseline/models/heads/custom_detr_head.py#L304) would fix the problem. We kindly ask you to try fixing this and contribute to our repo.

**Comment by faikit** [comment]
More relevant info:
- for te head, HungarianAssigner already has a normalization built inside.
- for lc head, LaneHungarianAssigner does not have one, a possible way might be passing the `range` to the LaneHungarianAssigner and doing the normalization inside.
