### ISSUE TITLE
#L243

### ISSUE THREAD

**Issue by yuanpengtu** [OpenDriveLab/OpenLane-V2#43]
https://github.com/OpenDriveLab/OpenLane-V2/blob/ddfcc55b871b490288815daf479e4224004148bf/plugin/mmdet3d/configs/baseline_large.py#L243
Are these settings(bev_range=[-50.0, -25.0, -3.0, 50.0, 25.0, 2.0], normalize=True) needed to add in this place as in baseline config?

**Comment by faikit** [comment]
Hi, no, the BEV range is specified by `point_cloud_range` in this config.
