### ISSUE TITLE
Question about the camera parameter transformation when resize the front view.

### ISSUE THREAD

**Issue by YuanxianH** [OpenDriveLab/OpenLane-V2#44]
Hi! Thank you for your contribution and I read your code carefully. My question is why `lidar2cam_rt` was transposed. (See in below link.)  
https://github.com/OpenDriveLab/OpenLane-V2/blob/ddfcc55b871b490288815daf479e4224004148bf/plugin/mmdet3d/baseline/datasets/pipelines/transforms.py#L78

As far as I know, the resize operation of the image will only change its intrinsic, and its extrinsic should be kept the same.

**Comment by faikit** [comment]
It seems that it just follows the practise [here](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/baseline/datasets/openlane_v2_dataset.py#L259) in the dataset.

**Comment by YuanxianH** [comment]
Well, I see. `lidar2cam_rt` is actually initialized in a transposed pattern. 🤣
