### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ldhai** [OpenDriveLab/OpenLane-V2#45]
在跑baseline配置时候，发现f_score.py文件中的from ortools.graph import pywrapgraph在启动训练时会引发**segmentation fault 错误** .
当在valuate.py文件中注释掉from .f_score import f1和etrics['F-Score for 3D Lane']['score'] = f1.bench_one_submit(gts=gts, preds=preds)这两句话时，可以正常启动训练。

想问一下大家有遇到这样的问题，是怎么解决的。

numpy==1.23.4
ortools==9.2.9972

**Comment by JianCui1992** [comment]
@ldhai 请问这个问题解决了吗？
