### ISSUE TITLE
Prediction format issue

### ISSUE THREAD

**Issue by Eralien** [OpenDriveLab/OpenLane-V2#46]
Hi, thank you for your work. I have an issue regarding the format prediction part during evaluation for val/test in [openlane_v2_dataset.py#L386](https://github.com/OpenDriveLab/OpenLane-V2/blob/ddfcc55b871b490288815daf479e4224004148bf/plugin/mmdet3d/baseline/datasets/openlane_v2_dataset.py#LL386C23-L386C23).

The code sorted lane centerline prediction by their confidence, and stored them in the output result dictionary. However, the [topology](https://github.com/OpenDriveLab/OpenLane-V2/blob/ddfcc55b871b490288815daf479e4224004148bf/plugin/mmdet3d/baseline/datasets/openlane_v2_dataset.py#L425) part did not get selected accordingly. I am not entirely sure, but based on the evaluation script function [_mAP_topology_lclc](https://github.com/OpenDriveLab/OpenLane-V2/blob/ddfcc55b871b490288815daf479e4224004148bf/openlanev2/evaluation/evaluate.py#LL416C7-L416C7), it seems that the sequence of lclc topology relies upon the lc pred.

If my observation is correct, a possible correction is:
```python
prediction['topology_lclc'] = result['pred_topology_lclc'][sorted_index][:, sorted_index]
prediction['topology_lcte'] = result['pred_topology_lcte'][sorted_index]
```

**Comment by faikit** [comment]
Another option would be deleting the [sorted_index](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/baseline/datasets/openlane_v2_dataset.py#L386)

**Comment by faikit** [comment]
I think it should be fine. For the results, it is required to keep the order of predictions corresponded to the order in adjacency matrix. This bug lead to a misalignment of the oreders.

Note that the TOP scores might not have an obvious change that reasoning about the topology relationship is a hard problem.
