### ISSUE TITLE
Confusions about the TOP

### ISSUE THREAD

**Issue by wangxinqun** [OpenDriveLab/OpenLane-V2#51]
Hi, thanks for the remarkable work!
I am confused about the TOP calculation.
![image](https://github.com/OpenDriveLab/OpenLane-V2/assets/23709418/92d92c7e-4626-4d1d-bf2c-8be20d19bb94)
1. In the paper, the meaning of the N (v) is explained as _the ordered list of neighbors of vertex v ranked by confidence_, but the vertex v seems to be the groundtruth, so I can not understand where does the _confidence_ come from? 
2. What does the N̂ ′ (v) mean? Could you explain that why the neighbors of vertex v need to be ranked by confidence? And could you show me the related codes?
Any helps are welcomed!

**Comment by faikit** [comment]
Hi,

1. the order is related to the P for precision;
2. N̂ means the predicted neighbors of the node v, and ' is for the matching process shown in the context.

**Comment by wangxinqun** [comment]
But it seems that the neighbors' list of every vertex v is the same, so what is the meaning of ranking the list?

**Comment by faikit** [comment]
Hi, it is for the predicted neighbors.

**Comment by wangxinqun** [comment]
Hi, I design the following example to explain how I understand the process, if I am wrong, please tell me.
Suppose that we have two lane centers, the groundtruth of the lane graph is:
                    **0 1
                    0 0**

Meanwhile, suppose that the matched predicted lane graph is :
                    **0.10  0.80
                    0.15  0.01**

Accoding to your paper, _"positive edges are those whose confidence is greater than 0.5"_.
So the one_hot predicted lane graph is 
                    **0 1
                    0 0**

For the first vertex 0, the predicted neighbors list is [0, 1] (The values of the edges are [0, 1]), 
and the ordered predicted neighbors list is [1, 0], because the confidence 0.80 > 0.10.

**Comment by faikit** [comment]
The example looks correct.
For the ordered predicted neighbors [1, 0], the order of the GT also changes to [1, 0].
I think the 7th slide [here](https://www.csie.ntu.edu.tw/~r01922164/SNA/Problems.pdf) would explain why we need to sort the neighbors according to their confidence.

**Comment by wangxinqun** [comment]
Thanks a lot, the slide you shared helped a lot.
Actually, according to your slide, my example is wrong, and the correct one should be as the following.

Suppose that we have two lane centers, the groundtruth of the lane graph is:
**0 1
0 0**

Meanwhile, suppose that the matched predicted lane graph is :
**0.10 0.80
0.15 0.01**

Accoding to your paper, "positive edges are those whose confidence is greater than 0.5".
So the one_hot predicted lane graph is
**0 1
0 0**

For the first vertex 0, the predicted neighbors list is **[1]**

**Comment by wangxinqun** [comment]
But I still have one more question.

Suppose that the ground truth of a vertex's neighbor list is [1 3]
And the matched, ordered, predicted list is [0 3].

According to your slide, the 𝐴𝑣𝑒𝑃 should be ( 0x1 + 1x0.5 ) x 0.5

My question is that, why do not we calculate it as:
( 0x1 + 1x1 ) x 0.5 ?

The difference is that, why the precision of the second vertex is 0.5, instead of 1?
Why must we consider the failure of the prediction of the first vertex when we calculate the precision of the second vertex?
I believe that this results that we have to consider the order of the predicted list.

Thank you.

**Comment by faikit** [comment]
If we do not consider precision, the model can simply predict all nodes as the neighbor, and achieve a perfect score, 1.
Such that the predicted results is [0, 1, 3], and the score would be ( 0x1 + 1x1 + 1x1 ) x 0.5 = 1

**Comment by wangxinqun** [comment]
A nice answer!
Thank you for your patience.

**Comment by linxcan** [comment]
> If we do not consider precision, the model can simply predict all nodes as the neighbor, and achieve a perfect score, 1. Such that the predicted results is [0, 1, 3], and the score would be ( 0x1 + 1x1 + 1x1 ) x 0.5 = 1

I have a question. If I predict that the probability of connecting [0,1,3] is [0.9,0.9,0.9], the probability calculated by the indicator is quite large, but the node 0 is the wrong connecting edge. There is nothing Punishment?

**Comment by faikit** [comment]
Hi, I dont quite get your question. Could you provide a more detailed description?

**Comment by zhangmanCN** [comment]
> If we do not consider precision, the model can simply predict all nodes as the neighbor, and achieve a perfect score, 1. Such that the predicted results is [0, 1, 3], and the score would be ( 0x1 + 1x1 + 1x1 ) x 0.5 = 1

Hi, I want to confirm if my understand is right.
Consider a vertex v:
the ground truth of v's neighbor list is [1, 3, 5, 9],
the predict of v's neighbor list is [2, 3, 5, 6, 8, 9],

so the score would be ( 0x1 + 1x1/2 + 1x2/3 + 0x2/4 + 0x2/5 + 1x3/6) x (1/4) = 5/12.

In the above equation, the 6 of the 3/6 means its the 6th predict neighbor, the 3 of the 3/6 meas there are 3 right results in the front 6 predict.
And the 4 of the 1/4 is means the ground truth list has 4 neighbor .

Do I have any mistake ? Please advise me.
