### ISSUE TITLE
Question Regarding the Pose to GPS Transformation

### ISSUE THREAD

**Issue by katieluo88** [OpenDriveLab/OpenLane-V2#52]
Thanks for the awesome dataset! I was wondering if the GPS location can be exposed? I was hoping to get the GPS location from the pose estimate, but in the AV2 dataset the city location is required to compute this projection. Is there any ways we can get which city a frame belongs to? Specifically, I was hoping to pull information at the location, which requires converting the city coordinates to WGS84 coordinates.

Thanks!

**Comment by sephyli** [comment]
Hi, thank you for using our dataset! 

In the meta data of each frame, we have annotated the corresponding `log_id` from the AV2 sensor dataset in `frame_info['meta_data']['source_id']`. 

```
{
    'version':                              <str> -- version
    'segment_id':                           <str> -- segment_id
    'meta_data': {
        'source':                           <str> -- name of the original dataset
        'source_id':                        <str> -- original identifier of the segment
    }
    ...
}
```

If you have access to the AV2 sensor dataset, you can use the following code to retrieve the city name and GPS information for each individual frame.

```python
import os
from glob import glob
from av2.geometry.utm import convert_city_coords_to_wgs84

# assuming olv2_frame_info is already loaded
split = 'train'
olv2_frame_info = ...

# get log_id in av2
av2_data_root = '/Path/To/Argoverse2/Sensor_Dataset/sensor/'
av2_log_id = olv2_frame_info['meta_data']['source_id']

# get cityname from av2
map_dir = os.path.join(av2_data_root, split, av2_log_id, 'map/')
map_file = glob(map_dir + 'log_map_archive_*')[0]
city_name = map_file.split("____")[1].split("_")[0]

# obtain wgs84 coordinate
points_city = olv2_frame_info['pose']['translation'][None, :2]
points_gps = convert_city_coords_to_wgs84(points_city, city_name)[0]
```

If you encounter any issues or have any questions, please feel free to reach out to us.

Thanks!

**Comment by katieluo88** [comment]
Thank you! This is exactly what I was looking for!
