### ISSUE TITLE
Checkpoint for baseline large

### ISSUE THREAD

**Issue by hagianga21** [OpenDriveLab/OpenLane-V2#59]
Thanks for the work, do you have any plan to release the checkpoint for the baseline large model? 
Moreover, I see you set samples_per_gpu=1, workers_per_gpu=8. That means the batch_size is 1 and the num_workers is 8? Am I missing something?

**Comment by faikit** [comment]
Hi, the batch size is 8 as we use 8 GPUs during training. The workers are for preparing data in the dataloader, which use CPUs and is not relevant to model training.

**Comment by hagianga21** [comment]
Thanks. so the output is 15 polyline points for each lane? Or Bezier control points?

**Comment by faikit** [comment]
Hi，there are polyline points.
________________________________
寄件者: hagianga21 ***@***.***>
寄件日期: Saturday, July 29, 2023 12:04:07 AM
收件者: OpenDriveLab/OpenLane-V2 ***@***.***>
副本: faikit ***@***.***>; Comment ***@***.***>
主旨: Re: [OpenDriveLab/OpenLane-V2] Checkpoint for baseline large (Issue #59)


Thanks. so the output is 15 polyline points for each lane? Or Bezier control points?

―

**Comment by hagianga21** [comment]
So to confirm, it will output 100 lanes, which have 15 polyline points?

**Comment by sephyli** [comment]
BaselineLarge model outputs 5 * (x, y, z) bezier control points, and the results will be interpolated to 11 equal-dist polyline points in the [dataset](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/models/baseline/datasets/openlane_v2_dataset.py#L401).
