### ISSUE TITLE
Baseline problem

### ISSUE THREAD

**Issue by PeggyPeppa** [OpenDriveLab/OpenLane-V2#6]
![捕获](https://user-images.githubusercontent.com/60730828/222427774-9f141203-1c98-45d4-aa53-4ffeb3cefaec.PNG)
Hi~ When training this baseline, I met such a problem. Do you have any suggestions or views on this problem？

**Comment by faikit** [comment]
Seems that the shape of the annotations does not match the expected shape, mayby you can print out the frame.get_annotations_traffic_elements() and [(split, segment_id, timestamp)](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/baseline/datasets/openlane_v2_dataset.py#L298) when the error occur.  The expected shape of element['points']  should be [2, 2]. This error maybe caused by the imcomplete downloaded data or some io error.

**Comment by yuanpengtu** [comment]
> ![捕获](https://user-images.githubusercontent.com/60730828/222427774-9f141203-1c98-45d4-aa53-4ffeb3cefaec.PNG) Hi~ When training this baseline, I met such a problem. Do you have any suggestions or views on this problem？

have you solved this? I have the same problem with you.

**Comment by faikit** [comment]
maybe you can provide us some info (https://github.com/OpenDriveLab/OpenLane-V2/issues/6#issuecomment-1451806700) so that we can have a look in the released data, as currently we don't have resources to try regenerating this problem.

**Comment by yuanpengtu** [comment]
frame.get_annotations_traffic_elements() : 
[{'id': 'tl_00', 'category': 1, 'attribute': 0, 'points': array([[ 289.95984,  980.3213 ],
       [ 300.4016 , 1002.00806]], dtype=float32)}, {'id': 'tl_01', 'category': 1, 'attribute': 0, 'points': array([[ 315.06024,  983.7349 ],
       [ 329.11646, 1001.80725]], dtype=float32)}, {'id': 'tl_02', 'category': 1, 'attribute': 0, 'points': array([[380.3213, 914.6586],
       [400.2008, 935.9438]], dtype=float32)}, {'id': 'tl_03', 'category': 1, 'attribute': 0, 'points': array([[410.24097, 911.4458 ],
       [420.68274, 938.9558 ]], dtype=float32)}, {'id': 'tl_04', 'category': 1, 'attribute': 0, 'points': array([[482.53012, 909.63855],
       [504.21686, 937.9518 ]], dtype=float32)}, {'id': 'tl_05', 'category': 1, 'attribute': 0, 'points': array([[287.1486 , 937.3494 ],
       [303.01205, 962.0482 ]], dtype=float32)}, {'id': 'rs_20', 'category': 0, 'attribute': 5, 'points': array([[507.39102, 893.107  ],
       [531.9066 , 921.40076]], dtype=float32)}, {'id': 'rs_21', 'category': 0, 'attribute': 4, 'points': array([[606.1846 , 890.8385 ],
       [629.57196, 920.62256]], dtype=float32)}]

**Comment by yuanpengtu** [comment]
Is the size of train folder the same with you? we got 225913544 when conducting ‘‘du -s’’ under train folder.

**Comment by qwertyczx** [comment]
Hi, I just downloaded the data. Here is my md5sum result:
![图片](https://user-images.githubusercontent.com/56955867/223913807-0b190633-7f73-4693-9e50-651d54b0af37.png)
Then I preprocessed data with data/OpenLane-V2/preprocess.py and train the baseline, and met the same problem.

**Comment by RicardLee** [comment]
Is the md5 of OpenLane-V2_subset_A_info.tar `d7b3553e8f06b7d4febb9e1ac133ec94` ?

**Comment by qwertyczx** [comment]
> Is the md5 of OpenLane-V2_subset_A_info.tar `d7b3553e8f06b7d4febb9e1ac133ec94` ?
Yes
![图片](https://user-images.githubusercontent.com/56955867/223927946-9c9c825f-056d-4741-b281-f911d5514c61.png)

**Comment by yuanpengtu** [comment]
same md5 and meet the same problem: d7b3553e8f06b7d4febb9e1ac133ec94

**Comment by PeggyPeppa** [comment]
> Is the size of train folder the same with you? we got 225913544 when conducting ‘‘du -s’’ under train folder.
Hi, I haven't fixed this problem. I checked my md5, it is the same as author provided. But after unzipping, I only got 121915044 files... I wonder is it something went wrong when I was unzipping the data.

**Comment by RicardLee** [comment]
Please wait on, we are checking this problem.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Peggy ***@***.***>
发送时间: Friday, March 10, 2023 2:24:33 PM
收件人: OpenDriveLab/OpenLane-V2 ***@***.***>
抄送: 李阳 ***@***.***>; Comment ***@***.***>
主题: Re: [OpenDriveLab/OpenLane-V2] Baseline problem (Issue #6)


Is the size of train folder the same with you? we got 225913544 when conducting ‘‘du -s’’ under train folder.
Hi, I haven't fixed this problem. I checked my md5, it is the same as author provided. But after unzipping, I only got 121915044 files... I wonder is it something went wrong when I was unzipping the data.

―

**Comment by RicardLee** [comment]
Hi,  the format error in data cause the problem and we have fix that in latest data.

**Comment by RicardLee** [comment]
Hi:
     The numbers of test  and val  folder are reght. But the train folder should be  "json 22477 and jpg 157339".
