### ISSUE TITLE
OpenLane-V2 2.0 plugin release plan and time frame?

### ISSUE THREAD

**Issue by henryzhangzhy** [OpenDriveLab/OpenLane-V2#62]
Hi, we are interested specifically in the 2.0 version of the dataset. I noticed that the plugins for working with the 2.0 version of the dataset are not yet available #61. Could you please share with us the plan and estimated time frame for releasing the plugin? It would also be great if you could update the [instructions ](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/docs/getting_started.md#train-a-model) to let the users know that the 2.0 plugins are not yet available.

Thank you!

**Comment by faikit** [comment]
Hi, thanks for the advices. The plugins will be available later this year.

**Comment by henryzhangzhy** [comment]
Thank you for letting me know and making it open-source!
