### ISSUE TITLE
SD map info

### ISSUE THREAD

**Issue by xiaowang12345** [OpenDriveLab/OpenLane-V2#65]
Hi, I downloaded and played w/ the SD-map.  Actually,  I found the SD-map only have road-level info, but not lane-level info.  The worst thing is that the SD-map do not have the topo info in the intersection (turn left, turn right..)

Would you plan to update the SD(ADAS)-map in the future?

**Comment by xiaowang12345** [comment]
> 
1. you mentioned SD map will give "topological and positional priors“， the gif of "SD map" also show the turn-right, turn-left, and lane split info.
2. however, the provided SD map do not have the info.  I think it is not so-called ADAS map.
3. we'd like to research the light map fusion...

**Comment by faikit** [comment]
Do you mean this gif? The right part does include turn-right, turn-left, and lane split info, but that's the annotations provided for centerlines or lane segements.
![image](https://github.com/OpenDriveLab/OpenLane-V2/assets/29263416/f2c40624-647d-43e0-8122-8d99c4924877)

Do you think that the road-level topology relationships would be critical for your purpose?

**Comment by xiaowang12345** [comment]
> 

 I think so....

**Comment by faikit** [comment]
Maybe we can schedule a meeting to have a discussion on that. Please send us an email to the address in the  [README](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/README.md) file.
