### ISSUE TITLE
ModuleNotFoundError: No module named 'openlanev2.dataset'

### ISSUE THREAD

**Issue by SecretMG** [OpenDriveLab/OpenLane-V2#67]
https://github.com/OpenDriveLab/OpenLane-V2/blob/bdd46b17638535d1818b48bc9f028bbfd77762a1/plugin/models/baseline/datasets/openlane_v2_dataset.py#L34C4-L34C4

I'm trying to train a model based on the instructions, but I got an unexpected error: ModuleNotFoundError: No module named 'openlanev2.dataset'.
I've modified the 'from openlanev2.dataset import Collection' to 'from openlanev2.centerline.dataset import Collection', and the next 3 lines in the same way, and it worked fine for now.
But is that right? Or it's actually due to some missing during my env configuration?

**Comment by faikit** [comment]
Hi, we have not updated the baseline model for the new version yet. You can try the [`v1.0`](https://github.com/OpenDriveLab/OpenLane-V2/tree/v1.0.0) dataset.
