### ISSUE TITLE
Different number of points in pre-processed GT labels.

### ISSUE THREAD

**Issue by jackiechenxd** [OpenDriveLab/OpenLane-V2#68]
Hi @faikit,

Thank you for sharing the GT labels and the pre-processing code. I have a few questions regarding the chosen number of sampled points during pre-processing.

Specifically, in the lane center dataset, I noticed that the train/val sets have 201 and 11 points respectively. I assume the 201 points aid in fitting the bezier curve with better accuracy, while the 11 points during evaluation align with the sampling process. However, in the latest lane segment dataset, the sampled points for the lane center, and the left/right lanelines have been adjusted to 10 and 20 points respectively. However, during evaluation, the bezier prediction is still resampled to 11 points, creating a discrepancy with the ground truth points.

Could you provide some insight into the considerations behind this decision? Thanks!

**Comment by faikit** [comment]
Hi, I think you are talking about the 11 points in the baseline model? It is just for the centerline.
For the Map Element Bucket, the baseline model has not been released yet. And we are planning to release the baseline.

**Comment by jackiechenxd** [comment]
Thanks for the prompt reply. Yes, the 11 points is from the centerline dataset and its baseline model.
The 10 and 20 points are from the preprocessing of lane segment dataset here: https://github.com/OpenDriveLab/OpenLane-V2/blob/master/data/OpenLane-V2/preprocess-ls.py#L41

Are these 10 / 20 points based on your unreleased new baseline model for the ls dataset?

**Comment by faikit** [comment]
Hi, the 10/20 point setting is for the evaluation. And yes, the baseline model for this has not yet been released.

The choice of point number is independent in the evaluation process and baseline model. For example, in the centerline setting, the number of points is set to 11 for evaluation, and we just set the point in the baseline model to 11. For the model, it is also good to set the number to, e.g., 21 and then downsample to 11 for the following evaluation preocess.
