### ISSUE TITLE
Can you release data_dict_subset_B.json?

### ISSUE THREAD

**Issue by wudongming97** [OpenDriveLab/OpenLane-V2#69]
Hi,

I see the results on subset_b are reported on TopoNet. Can you release data_dict_subset_B.json?  Thanks a lot!

**Comment by faikit** [comment]
Hi, we will have a look on that.

**Comment by wudongming97** [comment]
Hi, @faikit, have you found this file? This file is used in the preprocessing (https://github.com/OpenDriveLab/OpenLane-V2/blob/master/data/OpenLane-V2/preprocess.py), so it is necessary. Thanks!

**Comment by sephyli** [comment]
Hi, @wudongming97, the file is uploaded.

**Comment by wudongming97** [comment]
Hi, @faikit 

When running on subset_b, it has an error:
[Errno 2] No such file or directory: '/data/Dataset/openlanev2/train/01388/image/CAM_FRONT/1537290911412404.jpg'

I find it is because the OpenLane-V2_subset_B_image_3.tar (https://drive.google.com/file/d/1zjerxQ_gAVh-NkWi1erP5C6aeD6JB_Os/view) lacks some data. Could you please check this?
