### ISSUE TITLE
Pre-training model

### ISSUE THREAD

**Issue by YWonchall** [OpenDriveLab/OpenLane-V2#7]
HI! 
Thank you for running the competition! I would like to check if my code is correct, but it takes a long time to train the model. Can you provide a pre-training model?  Thank you!

**Comment by faikit** [comment]
Hi, currently, we did not plan to release the pre-trained ckpt. But pls stay tuned, we will make some notice in case of any updates.

It is recommended to do an overfitting to check your code.
For modifying the data_dict*.json, you could make a pickle for training by [preprocess](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/data/OpenLane-V2/preprocess.py), e.g., a pickle file with only 32 samples.
In my experience, it would take about a thousand epochs for a decent ckpt.
