### ISSUE TITLE
Missing some data on  OpenLane-V2_subset_B_image_3.tar 

### ISSUE THREAD

**Issue by wudongming97** [OpenDriveLab/OpenLane-V2#72]
Hi, @faikit

When running on subset_b, it has an error:
[Errno 2] No such file or directory: '/data/Dataset/openlanev2/train/01388/image/CAM_FRONT/1537290911412404.jpg'

I find it is because the OpenLane-V2_subset_B_image_3.tar (https://drive.google.com/file/d/1zjerxQ_gAVh-NkWi1erP5C6aeD6JB_Os/view) lacks some data. Could you please check this? #69

**Comment by PeggyPeppa** [comment]
Hi~ Thanks for your issue. We have reuploaded the OpenLane-V2_subset_B_image_3.tar. Please check!

**Comment by wudongming97** [comment]
So sorry. It still has missing files. 
[Errno 2] No such file or directory: '/data/Dataset/openlanev2/train/01080/image/CAM_FRONT/1533114284512460.jpg'

Checking this issue case by case is hard work, so could you please check the entire file list by designing a manuscript?

**Comment by wudongming97** [comment]
Hi, @PeggyPeppa, could you please check the entire released data?

**Comment by wudongming97** [comment]
Thank you so much！
