### ISSUE TITLE
Overlapping nuscenes / argoverse splits lead to overfitting.

### ISSUE THREAD

**Issue by Bochicchio3** [OpenDriveLab/OpenLane-V2#74]
I have a question regarding the dataset. In both nuscenes and argoverse dataset the training validation and test dataset contain overlapping sequences and this could lead to severe overfitting on static elements such as center and boundary lanes. New splits have been proposed for both datasets: 

argoverse: https://github.com/yuantianyuan01/streammapnet
nuscenes: https://github.com/tom-roddick/mono-semantic-maps/blob/master/src/data/nuscenes/splits.py

Both new splits try to minimize the spatial overlap between the sets.
How are the openlane splits for both nuscenes and argoverse created? Do you also use custom splits to minimize the cross contamination? 

Also, in argoverse, they mention some map changes in the following sequences:
"
However, a few Sensor Dataset logs intentionally feature HD map changes:

    75e8adad-50a6-3245-8726-5e612db3d165
    54bc6dbc-ebfb-3fba-b5b3-57f88b4b79ca
    af170aac-8465-3d7b-82c5-64147e94af7d
    6e106cf8-f6dd-38f6-89c8-9be7a71e7275
"

These sequences were not removed when creating the openlane dataset, right?

I believe there is also the same problem with some of the sequences in nuscenes, but I am not entirely sure.

**Comment by sephyli** [comment]
Hi, @Bochicchio3. Thank you for bringing this up.

Regarding the splits for OpenLane-V2, they are the same as the Argoverse 2 and nuScenes raw split. To address the overfitting issue, we have created a `geo-isolation` validation subset. You can find more details about it in [this issue](https://github.com/OpenDriveLab/TopoNet/issues/3) and an early version of TopoNet [paper](https://arxiv.org/pdf/2304.05277v1.pdf).

Regarding the map change problem, the sequences were not removed. Removing them should lead to an improvement in overall performance, especially in traffic element detection. You can find more information about this in this [repo](https://github.com/OpenDriveLab/TopoNet/blob/0965853b65272183d53331bb3db6e59c87846754/projects/toponet/datasets/openlanev2_subset_A_dataset.py#L38C3-L38C3).

**Comment by sephyli** [comment]
Noticed that, during the process of curating the OpenLane-V2 subset-B, we identified certain scenes from the nuScenes dataset that had localization issues and missing labels. We have taken the necessary steps to remove these problematic scenes from the dataset.
The `scene_id` of nuScenes is:
```
a6daedc3063b421cb3a05019e545f925
02f1e5e2fc544798aad223f5ae5e8440
55638ae3a8b34572aef756ee7fbce0df
20ec831deb0f44e397497198cbe5a97c
```
