### ISSUE TITLE
Confusions about the TOP_ll

### ISSUE THREAD

**Issue by zhangmanCN** [OpenDriveLab/OpenLane-V2#75]
Hi, the OpenLane-V2 is a great job, and I want to confirm if my understand is right about #51 
To the TOP_ll, consider a vertex v:
the ground truth of v's neighbor list is [1, 3, 5, 9],
the predict of v's neighbor list is [2, 3, 5, 6, 8, 9],

so the score would be ( 0x1 + 1x1/2 + 1x2/3 + 0x2/4 + 0x2/5 + 1x3/6) x (1/4) = 5/12.

In the above equation, the 6 of the 3/6 means its the 6th predict neighbor, the 3 of the 3/6 meas there are 3 right results in the front 6 predict.
And the 4 of the 1/4 is means the ground truth list has 4 neighbor .

Do I have any mistake ? Please advise me.

**Comment by faikit** [comment]
Hi, I think the calculation is correct.

**Comment by zhangmanCN** [comment]
> Hi, I think the calculation is correct.

Thank you for your reply !

In fact , if the above calculation is right, I have another question.

Refer to the paper and  #51, the meaning of the N (v) is explained as the ordered list of neighbors of vertex v ranked by confidence.

In my understance,  consider a vertex v:
It has a neighbor b in the ground truth, and it has a neighbor b' in the predict. 
As the same time ,the confidence of the edge in the predict between v and b' is P(b'). And the b is matched with b' by similarity measures(to line centers, the similarity measures is Frechet distance)

So the neighbor b would be ranked in the ground truth by the confidence P(b').

Do I have any mistake ? Please advise me.

If it's right, if the neighbor c in the ground truth can not find a matched in the predict, how to calculate the confidence of the neighbor c when rank in the ground truth? According to the code, it seems to be set to 1?

Looking forward to your reply~

**Comment by faikit** [comment]
Hi, 

about the N(v), there is a typo in the current version. As we can see in the formula, the order do not have impact for the N() operator.

> the confidence of the edge in the predict between v and b' is P(b')

P() is the precision of the predicted node. Actually, the important thing is the confidence of predicted neighbors, such as [2, 3, 5, 6, 8, 9] or [9, 2, 3, 5, 6, 8].
