### ISSUE TITLE
Can we build associations with gt of nuScenes' 3D detection?

### ISSUE THREAD

**Issue by exiawsh** [OpenDriveLab/OpenLane-V2#78]
Hello, thank you for your great work! May I ask if you keep association with the sample token of nuScenes in subset B? Is it possible to use both topology annotation and 3D detection annotation simultaneously?

**Comment by faikit** [comment]
Currently we only have association between static elements. 

But I think it is possible to extend association to dynamic objects. Do you suggest the positional association between them or some other kinds of association?

**Comment by exiawsh** [comment]
@faikit Thank you for the response! I'm sorry. I mean, for the same scene, I want to obtain the gts of dynamic objects (in the original nuscenes) and  static elements (in your work). Do you keep some interface (e.g. sample token, timestamp, scene token)?

**Comment by exiawsh** [comment]
It seems that the source_id is the same as the sample token in nuscenes?

**Comment by sephyli** [comment]
Hello,

In OpenLane-V2, the `source_id` corresponds to the `scene_token` in nuScenes. We have not recorded the `sample_token`, but you can correlate samples from OpenLane-V2 with those from nuScenes using the `scene_token` and `timestamp`. Additionally, please note that the timestamps in OpenLane-V2 are aligned with the front-view camera.

**Comment by exiawsh** [comment]
> Hello,
> 
> In OpenLane-V2, the `source_id` corresponds to the `scene_token` in nuScenes. We have not recorded the `sample_token`, but you can correlate samples from OpenLane-V2 with those from nuScenes using the `scene_token` and `timestamp`. Additionally, please note that the timestamps in OpenLane-V2 are aligned with the front-view camera.

Thank you so much! I will try.

**Comment by sephyli** [comment]
Additionally, you may be interested to know that some scenes are missing in OpenLane-V2 subset-B due to the absence of certain annotations. For more information, please see issue #74.

**Comment by exiawsh** [comment]
@sephyli Sorry to bother you again. The gts of the centerlines are in imu or lidar coordinate?

**Comment by sephyli** [comment]
The centerline GTs' coordinate is in imu/ego coordinare.

**Comment by faikit** [comment]
![image](https://github.com/OpenDriveLab/OpenLane-V2/assets/29263416/e1b93143-bd17-4aef-94c2-b71acb95bf26)

**Comment by exiawsh** [comment]
@faikit @sephyli Thank you!
