### ISSUE TITLE
Road Lane

### ISSUE THREAD

**Issue by koughua** [OpenDriveLab/OpenLane-V2#8]
Hi, thanks for the amazing work!

I want to confirm whether the annotations only contains the centerline of the lane and does not contain the lane line label information, because I did not find it in the labeling file but you metioned "Following the [OpenLane](https://github.com/OpenDriveLab/OpenLane) dataset, we annotate lanes in 3D space to reflect their properties in the real world." in the Readme.

if no, Will it be provided later or how to obtain it?

**Comment by faikit** [comment]
yes, we inherit the spirit of annotating lanes in 3D space, but we regard the conceptual centerlines a better representation for downstream tasks instead of the visible lanelines.
