### ISSUE TITLE
The 3D space annotation of map element in SubB

### ISSUE THREAD

**Issue by BellCHENG** [OpenDriveLab/OpenLane-V2#80]
Hi,

I found that the values of "z-axis" of map elements in subB dataset are all zero, so may I know if you will release the 3D space annotation of map element in subB dataset?

Thanks.

**Comment by faikit** [comment]
Hi, as the HD maps in subset-B do not contain height information, we set the z-axis in this subset by default as 0.

**Comment by BellCHENG** [comment]
Got it and great thankfulness to your work and your reply.
