### ISSUE TITLE
Question about lane segment definition

### ISSUE THREAD

**Issue by Reeki67** [OpenDriveLab/OpenLane-V2#81]
Hello,
 I wonder what’s the definition of a lane segment. The points in the red box do not represent forks or merges, nor are they located at junctions. Why can they divide a centerline?
![20231127-180948](https://github.com/OpenDriveLab/OpenLane-V2/assets/140675442/f3f2b55b-9570-4e51-b629-989b445deea2)

**Comment by sephyli** [comment]
Hi, thanks for your question.
If you're referring to our latest lane segment representations, a lane segment's breakpoint typically occurs at forks, merges, intersections, or when there's a change in laneline type. In your specific situation, the laneline type might vary before and after the breakpoint.
