### ISSUE TITLE
Confusion about topo_lcte

### ISSUE THREAD

**Issue by eeeric1** [OpenDriveLab/OpenLane-V2#83]
Hello, thank you for your work. 
I have some confusion about the topology metric. Take topology_lcte as an example:
When calculating the topology index, the matching results between gt and pred in lc/te is actually obtained first. I understand that when calculating the matching results, more attention is paid to the recall rate of te. The more bboxes recalled, the advantage will be when calculating the topology metric. Is the topology metric more affected by the detection recall rate than the precision rate?

**Comment by faikit** [comment]
Hi, 
as the TOP score is adapted from the graph domain, we first need a predicted graph that has the same number of vertices as in the GT graph. So we need a matching process at the beginning.
For unmatched vertices in the predicted graph, we use a dummy vertex to replace it.

**Comment by eeeric1** [comment]
Thanks for your reply, I still have some confusions.
If the te matching is more accurate, the recall rate is higher, then the predicted graph would not use dummy vertex, which should be more conducive to the TOP score in my view.
Then the model may prefer recall rather than precision when detecting traffic elements.

**Comment by faikit** [comment]
Yes or no. When considering the TOP score only, increasing recall would lead to a better matching.

**Comment by eeeric1** [comment]
Thanks for your reply.
Can I understand that DET scores focus more on pr, while TOP scores focus more on DET recall?

**Comment by faikit** [comment]
I would not use 'more', each metric has its own function.
