### ISSUE TITLE
does current plugin model support the v2.0x or the format of Map Element Bucket annotation?

### ISSUE THREAD

**Issue by yangsenius** [OpenDriveLab/OpenLane-V2#85]
Hi, thanks for this work!

When i load the data with sdmap,  the plugin/models/baseline/datasets/openlane_v2_dataset.py seemed to not take into the consideration the existence of 'sd_map', and tried to use the `self.meta['sensor'][camera]['extrinsic']` to load the `sd_map` information. Then i met the errors below:

```
  File "/root/openlanev2/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 435, in __getitem__
    data = self.prepare_train_data(idx)
  File "/root/openlanev2/mmdetection3d/projects/openlanev2/baseline/datasets/openlane_v2_dataset.py", line 326, in prepare_train_data
    input_dict = self.get_data_info(index)
  File "/root/openlanev2/mmdetection3d/projects/openlanev2/baseline/datasets/openlane_v2_dataset.py", line 250, in get_data_info
    lidar2cam_r = np.linalg.inv(frame.get_extrinsic(camera)['rotation'])
  File "/root/openlanev2/v1.0/OpenLane-V2/openlanev2/dataset/frame.py", line 133, in get_extrinsic
    return self.meta['sensor'][camera]['extrinsic']
KeyError: 'extrinsic'
```

Is this because the current plugin model is not prepared for using sdmap information? hope someone can provide an answer.

**Comment by yangsenius** [comment]
It seems that the current version of the plugin model doesn't support the format of the annotation of `Map Element Bucket` https://github.com/OpenDriveLab/OpenLane-V2/blob/master/data/README.md#map-element-bucket, when I evaluated the baseline model.

Is there any plan for update the version of plugin model?

**Comment by faikit** [comment]
Hi, the release of the open-source model on the update is on our plan and will be processed soon.

**Comment by yangsenius** [comment]
thanks, nice work
