### ISSUE TITLE
what is the forward direction of the vehicle？x or y

### ISSUE THREAD

**Issue by yangsenius** [OpenDriveLab/OpenLane-V2#86]
According to the described configuration of the "baseline_large", the "bev_h_" =100 and "bev_w_" =200. But when visualizing the GT and Pred, the coordinate[1] is the x-axis, and the coordinate[0] is the y-axis. 

So, what is the forward direction of the vehicle？X-axis?

**Comment by sephyli** [comment]
Hi, for both subsets, we use ego/imu coordinate system. The forward direction is x-axis. And the points of lane GT is in (x, y, z) format.
![coord](https://private-user-images.githubusercontent.com/29263416/280219521-e1b93143-bd17-4aef-94c2-b71acb95bf26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzgyMjMsIm5iZiI6MTcwMzU3NzkyMywicGF0aCI6Ii8yOTI2MzQxNi8yODAyMTk1MjEtZTFiOTMxNDMtYmQxNy00YWVmLTk0YzItYjcxYWNiOTViZjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MmNmYzBiYWQ2MzdhZGQ2MTUyMTA3Y2EwMzdiOTRiOTkzMmNiMTdhMDc2ODIxN2NkYTJiNGU2YmViODY3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6yx1waduzyHKgQmNv_0I1LkzmBRDgbghEtT3VFHTbec)

In baseline code, we use BEVFormer as BEV Encoder. The bev_h is refers to y-axis and the bev_w is refers to x-axis. If you are visualizing the lane on the BEV image using cv2, you may need to double-check the coordinates mapping.

**Comment by yangsenius** [comment]
Thanks. Is that means the grids in the left-direction of the current bev feature represent the forward-direction of the ego?
