### ISSUE TITLE
Confusion about the assignment rules for lane traffic topology

### ISSUE THREAD

**Issue by exiawsh** [OpenDriveLab/OpenLane-V2#87]
Hi, thanks for your great work.
In this scenario, the go straight sign is **only placed on the segment of the middle lane that is closer to us**. So, why isn’t the sign placed on segments of the lane that are further away (In fig. 2)? Is there a default rule that assigns traffic signs to the road segments closer to the vehicle? Based on this rule, can we assume that the lane where this segment is located is designated for going straight, and thus we don’t need to delve into which specific segment within the same lane should be assigned?

![output](https://github.com/OpenDriveLab/OpenLane-V2/assets/74858581/bcf1de0e-46b3-4b3d-b6ae-871bbc7c56e7)
![output1](https://github.com/OpenDriveLab/OpenLane-V2/assets/74858581/0eccd4f4-236f-4be0-a0e6-62c34f624945)

**Comment by faikit** [comment]
Hi, could you provide the identifier of the frame, so that we can have a closer look?
