### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by lucianzhong** [OpenDriveLab/OpenLane-V2#88]
Hi, thanks for this great work.

By given custom dataset's camera intrinsic and extrinsic, is it possible to inference directly without training the model?

Best regards

**Comment by faikit** [comment]
Please consider the domain gap between training and inference data.

**Comment by sephyli** [comment]
Hi, if I understand correctly, you are interested in performing zero-shot transfer with models trained on OpenLane-V2. Similar to all 3D AD datasets, the main challenge of this transfer lies in the overfitting to camera parameters within BEV Encoder. There have been studies exploring this transfer, which you can further investigate.

Additionally, for the task of scene understanding, road structure significantly differ among different countries and regions, posing another major obstacle for zero-shot transfer.

**Comment by lucianzhong** [comment]
Thanks for the replay. Yes, zero-shot transfer. I am going to learn more about it.

**Comment by lucianzhong** [comment]
@faikit  Thanks for the replay.  domain gap, such as different data scenes and FOV of the camera
