### ISSUE TITLE
Question about the 'is_intersection_or_connector' of 'lane_segment'

### ISSUE THREAD

**Issue by zhangmanCN** [OpenDriveLab/OpenLane-V2#89]
Thank you for your update on Map Element Bucket, it is greatly helpful for me. And I have a question about the annotation message.
In the annotation files of  Map Element Bucket, as follow:

```
    'lane_segment': [                       (i lane segments in the current frame)
        {   
            'id':                           <int> -- unique ID in the current frame
            'centerline':                   <float> [n, 3] -- 3D coordiate
            'left_laneline':                <float> [n, 3] -- 3D coordiate
            'left_laneline_type':           <int> -- type of the left laneline
                                                0: 'none',
                                                1: 'solid',
                                                2: 'dash',
            'right_laneline':               <float> [n, 3] -- 3D coordiate
            'right_laneline_type':          <int> -- type of the right laneline
            'is_intersection_or_connector': <bool> -- whether the lane segment is in a intersection or connector
            'confidence':                   <float> -- confidence, only for prediction
        },
        ...
    ]
```

I have doubts about the definition of  'connector'. For example, For two parallel straight lanes with a dashed line in the middle, which means that vehicles can change lanes between the two lanes. In the annotated data, would this be labeled as four lanes, with two straight lanes and two merging lanes? Are the merging lanes considered as 'connector'

**Comment by sephyli** [comment]
No, the 'is_intersection_or_connector' is not annotated on the laneline level.

**Comment by zhangmanCN** [comment]
> No, the 'is_intersection_or_connector' is not annotated on the laneline level.

Thank you for your reply. According to your reply, the 'is_intersection_or_connector' is annotated on the frame level? And it means if the frame including intersection or connector?
Looking forward to your reply～

**Comment by sephyli** [comment]
Sorry for the misleading. The 'is_intersection_or_connector' is annotated on the **lane** level, instead of **laneline** level.
