### ISSUE TITLE
 likely dataset on the carla simulator

### ISSUE THREAD

**Issue by raozhongyu** [OpenDriveLab/OpenLane-V2#91]
Hi, I'd like  the train the model  in the carla simulator, Can you give me some suggestions on how to generate a likely dataset on the carla simulator

**Comment by sephyli** [comment]
Hello, from my basic understanding of Carla, you can easily obtain a scene's centerline and connection information from its HDMap. 
Regarding 2D traffic elements, you might be able to project CARLA's 3D labels onto images and then generate the relationship between traffic elements and lanes through certain rules. 
However, it's important to note that re-annotating all categories from OpenLane-V2 in CARLA is unlikely, as CARLA does not provide 3D labels for all categories of traffic elements. 
If you have any better ideas or progress, feel free to discuss them with us at any time.
