### ISSUE TITLE
How to get real lanelines from the lane segment annotation?

### ISSUE THREAD

**Issue by wenjie710** [OpenDriveLab/OpenLane-V2#92]
Hi, as is illustrated in the paper, OpenLane-V2 subset A is built basd on Argoverse 2. Then how to get real lanelines in argoverse 2 from the lane segment annotation in OpenLane-V2? 
I found that some left lanelines and right lanelines in lane segments are virtual lanelines. How to distinguish the real lanelines from the virtual ones?

**Comment by sephyli** [comment]
Hi, @wenjie710, you can use the `laneline_type` to distinguish the virtual lane. The category 'none' refers to virtual lanelines.
For more details, please move to [here](https://github.com/OpenDriveLab/OpenLane-V2/tree/master/data#map-element-bucket).

**Comment by wenjie710** [comment]
Thanks a lot.
