### ISSUE TITLE
About Downloading Data via CLI

### ISSUE THREAD

**Issue by 1uciusy** [OpenDriveLab/OpenLane-V2#94]
I'm using CLI to download the dataset, but the last command seems not correct.
The command is `openxlab dataset download --dataset-repo OpenDriveLab/OpenLane-V2 --source-path/README.md --target-path /path/to/local/folder #数据集文件下载`.
After previous commands executed, the folders are like
```
.
└── OpenDriveLab___OpenLane-V2
    ├── metafile.yaml
    ├── raw
    ├── README.md
    ├── sample
    └── target
```

The first problem is `README.md` is not specific, whether it's the `README.md` of this repository or the `README.md` in the folder? I prefer the latter.
The second problem is  the `--sorce-path` and `/README.md` are connected.

So I run the command `openxlab dataset download --dataset-repo OpenDriveLab/OpenLane-V2 --source-path ./OpenDriveLab___OpenLane-V2/README.md --target-path ./`
I got the traceback as follows.
```
Traceback (most recent call last):
  File "/home/lucius.yang/miniconda3/envs/openlanev2/lib/python3.8/site-packages/openxlab/cli.py", line 100, in main
    return args.handler(args)
  File "/home/lucius.yang/miniconda3/envs/openlanev2/lib/python3.8/site-packages/openxlab/dataset/commands/download.py", line 44, in take_action
    download(
  File "/home/lucius.yang/miniconda3/envs/openlanev2/lib/python3.8/site-packages/openxlab/dataset/handler/download_dataset_repository.py", line 41, in download
    data_dict = client.get_api().get_dataset_files(
  File "/home/lucius.yang/miniconda3/envs/openlanev2/lib/python3.8/site-packages/openxlab/dataset/client/api.py", line 46, in get_dataset_files
    rprint(f"{OpenDataLabError(error_msg=highlight_urls(result_dict['toast']))}")
  File "/home/lucius.yang/miniconda3/envs/openlanev2/lib/python3.8/site-packages/openxlab/dataset/utils.py", line 106, in highlight_urls
    urls = find_url(text=text)
  File "/home/lucius.yang/miniconda3/envs/openlanev2/lib/python3.8/site-packages/openxlab/dataset/utils.py", line 93, in find_url
    urls = re.findall(r'(https?://[^"]+)', text)
  File "/home/lucius.yang/miniconda3/envs/openlanev2/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```

Could you tell me how to fix it?  
Many Thanks!

**Comment by up-pika** [comment]
About the last problem, the command "openxlab dataset download --dataset-repo OpenDriveLab/OpenLane-V2 --source-path ./OpenDriveLab___OpenLane-V2/README.md --target-path ./"  is not right. if you want to download README.md of your repository, you can try "openxlab dataset download --dataset-repo OpenDriveLab/OpenLane-V2 --source-path /README.md --target-path ./"， do not need add “./OpenDriveLab___OpenLane-V2” before “/README.md". you can get the path from ls command of openxlab dataset.

**Comment by 1uciusy** [comment]
> About the last problem, the command "openxlab dataset download --dataset-repo OpenDriveLab/OpenLane-V2 --source-path ./OpenDriveLab___OpenLane-V2/README.md --target-path ./" is not right. if you want to download README.md of your repository, you can try "openxlab dataset download --dataset-repo OpenDriveLab/OpenLane-V2 --source-path /README.md --target-path ./"， do not need add “./OpenDriveLab___OpenLane-V2” before “/README.md". you can get the path from ls command of openxlab dataset.

Of course I'm not trying to download `README.md`. It's because `README.md` is used in the sample code after `source-path`, So I suspect there might be some parameters need to be decoded from `README.md`. 

So, if I understand this right, the `sorce-path` means a remote path hosted by OpenXLab?

Many thanks

**Comment by 1uciusy** [comment]
I might solve this problem by `openxlab dataset download --dataset-repo OpenDriveLab/OpenLane-V2 --source-path / --target-path ./`.

It seems I'm downloading from the `source-path` of  repo `OpenDriveLab/OpenLane-V2` onto my local `target-path`
