### ISSUE TITLE
Do you have plan to open the visualization code on OpenLaneV2SubsetBDataset? :)

### ISSUE THREAD

**Issue by Benson722** [OpenDriveLab/OpenLane-V2#95]
When I try to visualize the model output on OpenLaneV2SubsetBDataset, I don't find the relative code. 

What I only find is the func "`visualize`" in "`OpenLane-V2/plugin/models/baseline/datasets/openlane_v2_dataset.py`". 

Do you have plan to open the visualization code about OpenLaneV2SubsetBDataset? :)

**Comment by faikit** [comment]
Hi, maybe you can try the one in devkit `OpenLane-V2/openlanev2/centerline/visualization`.
