### ISSUE TITLE
problem about visualization

### ISSUE THREAD

**Issue by Miranda0920** [OpenDriveLab/OpenLane-V2#97]
When I use openlanev2/lanesegment/visualization/pv.py to visualize groudtruth, I don't wanna draw lines between left_laneline and right_laneline. But the following comments are not valid:
```
def _draw_lane_segment(image, lane_segment, intrinsic, extrinsic, with_attribute, with_linetype, with_centerline, with_laneline):
    if with_centerline:
        _draw_line(image, {'points': lane_segment['centerline'], 'attributes': lane_segment['attributes']}, intrinsic, extrinsic, with_attribute, False)
    if with_laneline:
        _draw_line(image, {'points': lane_segment['left_laneline'], 'linetype': lane_segment['left_laneline_type']}, intrinsic, extrinsic, False, with_linetype)
        _draw_line(image, {'points': lane_segment['right_laneline'], 'linetype': lane_segment['right_laneline_type']}, intrinsic, extrinsic, False, with_linetype)
        # _draw_line(image, {'points': np.array([lane_segment['left_laneline'][0], lane_segment['right_laneline'][0]])}, intrinsic, extrinsic, False, False)
        # _draw_line(image, {'points': np.array([lane_segment['left_laneline'][-1], lane_segment['right_laneline'][-1]])}, intrinsic, extrinsic, False, False)

```

The result of _draw_lane_segment is still shown as below
(I don’t want to show the blue horizontal line in the picture)
![企业微信截图_17066724341852](https://github.com/OpenDriveLab/OpenLane-V2/assets/19873896/8c56cf4c-1720-497e-8fc4-3fd3eee0e084)

**Comment by sephyli** [comment]
If you have already commented the two lines of code, it should not draw the blue horizontal line. You can check if the code is you are running or not, e.g., if you install the openlanev2 in -e mode.

**Comment by Miranda0920** [comment]
> If you have already commented the two lines of code, it should not draw the blue horizontal line. You can check if the code is you are running or not, e.g., if you install the openlanev2 in -e mode.

Thanks for reply. I've solved the problem by recreating virtual env.
