### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by spcrobocar** [OpenDriveLab/OpenLane-V2#99]
In the download command 
`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=[FILE_ID]' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=[FILE_ID]" -O [FILE_NAME]`

What is the FILE_ID and FILE_NAME?

**Comment by faikit** [comment]
Hi, you can find the required strings after opening a file on the browser.
![image](https://github.com/OpenDriveLab/OpenLane-V2/assets/29263416/14e6caf3-3739-4810-9206-9382e023bf86)
